# Generated by Django 3.2.9 on 2021-12-07 08:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.SmallIntegerField(choices=[(0, 'continue watching'), (1, 'My List'), (2, 'Romantic Movies'), (3, 'Trending Now'), (4, 'Asian TV Drama'), (5, 'Netflix Originals'), (6, 'Hindi Movies'), (7, 'Action Movies')])),
                ('image_path', models.URLField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
